# Generated by Django 3.2.6 on 2021-08-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='email',
            new_name='user_id',
        ),
    ]
