# Generated by Django 3.2.6 on 2021-09-01 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_rename_email_store_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='content', max_length=200, null=True)),
                ('updt_dt', models.DateTimeField(auto_now=True, db_column='updt_dt')),
                ('insrt_dt', models.DateTimeField(auto_now_add=True, db_column='insrt_dt')),
                ('usage_fg', models.CharField(blank=True, db_column='usage_fg', default='Y', max_length=1, null=True)),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='board.store')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('tag_content', models.CharField(db_column='tag_content', max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'Product'), (2, 'Bowl')], db_column='type', default=1)),
                ('updt_dt', models.DateTimeField(auto_now=True, db_column='updt_dt')),
                ('insrt_dt', models.DateTimeField(auto_now_add=True, db_column='insrt_dt')),
                ('usage_fg', models.CharField(blank=True, db_column='usage_fg', default='Y', max_length=1, null=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='board.review')),
            ],
            options={
                'db_table': 'tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReviewImg',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('review_img', models.CharField(blank=True, db_column='review_img', max_length=200, null=True)),
                ('updt_dt', models.DateTimeField(auto_now=True, db_column='updt_dt')),
                ('insrt_dt', models.DateTimeField(auto_now_add=True, db_column='insrt_dt')),
                ('usage_fg', models.CharField(blank=True, db_column='usage_fg', default='Y', max_length=1, null=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='board.review')),
            ],
            options={
                'db_table': 'review_img',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('menu', models.CharField(db_column='menu', max_length=45)),
                ('updt_dt', models.DateTimeField(auto_now=True, db_column='updt_dt')),
                ('insrt_dt', models.DateTimeField(auto_now_add=True, db_column='insrt_dt')),
                ('usage_fg', models.CharField(blank=True, db_column='usage_fg', default='Y', max_length=1, null=True)),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='board.store')),
            ],
            options={
                'db_table': 'menu',
                'managed': True,
            },
        ),
    ]
