# Generated by Django 3.2.6 on 2021-09-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_store_color_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='color_index',
        ),
        migrations.AddField(
            model_name='tag',
            name='color_index',
            field=models.IntegerField(blank=True, db_column='color_index', null=True),
        ),
    ]
