# Generated by Django 3.2.6 on 2021-09-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_menu_review_reviewimg_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewimg',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='review_id',
            new_name='review',
        ),
    ]
