# Generated by Django 3.2.6 on 2021-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210901_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='latitude', decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=10, max_digits=13, null=True),
        ),
    ]
