# Generated by Django 3.2.6 on 2021-09-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210907_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImg',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('store_img', models.CharField(blank=True, db_column='store_img', max_length=200, null=True)),
                ('updt_dt', models.DateTimeField(auto_now=True, db_column='updt_dt')),
                ('insrt_dt', models.DateTimeField(auto_now_add=True, db_column='insrt_dt')),
                ('usage_fg', models.CharField(blank=True, db_column='usage_fg', default='Y', max_length=1, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='board.store')),
            ],
            options={
                'db_table': 'store_img',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuImg',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('menu_img', models.CharField(blank=True, db_column='menu_img', max_length=200, null=True)),
                ('updt_dt', models.DateTimeField(auto_now=True, db_column='updt_dt')),
                ('insrt_dt', models.DateTimeField(auto_now_add=True, db_column='insrt_dt')),
                ('usage_fg', models.CharField(blank=True, db_column='usage_fg', default='Y', max_length=1, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='board.menu')),
            ],
            options={
                'db_table': 'menu_img',
                'managed': True,
            },
        ),
    ]
