# Generated by Django 3.2.6 on 2021-09-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210902_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='latitude', decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=15, max_digits=18, null=True),
        ),
    ]
